name = input("What is your name? : ")
print(f"Hello, {name} ! Welcome to Python programming :)")
concept = input("What is your favorite programming concept ? : ")
print(f"Great, {concept} is a very important concept in programming !")
why =input(f"Why do you like {concept} ? : ")
print(f"Interesting, {why} !")
reason = input(f"Can you give me one more reason why you like {concept} ? : ")
print(f"Wow, {reason} is also a great reason to like {concept} !")  
which_year_student = input("Which year student are you ? : ")
print(f"Great, you are a {which_year_student} year student !")
greeting = input("What is your favorite greeting ? : ")
print(f"{greeting} to you too, {name} !")