user_name = input("enter your name ? : ")
# r = len(user_name)
# print(user_name.count("i"))
# print(user_name.upper())
# print(user_name.lower())
# print(user_name.capitalize())
# print(user_name.replace("i","a")
# print(user_name.find("i"))
# r = user_name.isdigit()
# print(r)
r = user_name.isalpha()
print(r)
